params = {"train_source_path":'homework_machine_translation_de-en/train.de-en.de',
          "train_target_path":'homework_machine_translation_de-en/train.de-en.en',
          "val_source_path":'homework_machine_translation_de-en/val.de-en.de',
          "val_target_path":'homework_machine_translation_de-en/val.de-en.en',
          "test_path":'homework_machine_translation_de-en/test1.de-en.de',
          "output_path":'test1_final50.de-en.en',
          "warmup_steps":8000,
          "d_model":256,
          "clip":1,
          "n_epochs":30,
          "min_freq":10,
          "batch_size":100}